spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=pharmacie-service
spring.cloud.gateway.routes[0].uri=lb://PHARMACIE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/medicaments/**

spring.cloud.gateway.routes[1].id=dossier-medical-service
spring.cloud.gateway.routes[1].uri=lb://DOSSIER-MEDICAL-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/dossiers/**

spring.cloud.gateway.routes[2].id=rendezvous-service
spring.cloud.gateway.routes[2].uri=lb://RENDEZVOUS-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/rendezvous/**

spring.cloud.gateway.routes[3].id=user-management-service
spring.cloud.gateway.routes[3].uri=lb://USER-MANAGEMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/users/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

logging.level.org.springframework.cloud.gateway=DEBUG