spring.application.name=config-server

server.port=8888

# Eureka registration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

# Config server - load configs locally
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=classpath:/config